# Generated by Django 3.1.8 on 2021-05-16 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='won',
            field=models.BooleanField(blank=True, null=True, verbose_name='Unsettled bet'),
        ),
    ]
