# Generated by Django 3.1.8 on 2021-05-20 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210516_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('draft_id', models.IntegerField()),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='event',
            options={},
        ),
        migrations.RemoveField(
            model_name='bet',
            name='chosen_result',
        ),
        migrations.RemoveField(
            model_name='bet',
            name='creation_time',
        ),
        migrations.RemoveField(
            model_name='bet',
            name='event',
        ),
        migrations.RemoveField(
            model_name='bet',
            name='odd',
        ),
        migrations.RemoveField(
            model_name='bet',
            name='open',
        ),
        migrations.RemoveField(
            model_name='bet',
            name='value',
        ),
        migrations.RemoveField(
            model_name='bet',
            name='won',
        ),
        migrations.RemoveField(
            model_name='event',
            name='author',
        ),
        migrations.RemoveField(
            model_name='event',
            name='away_name',
        ),
        migrations.RemoveField(
            model_name='event',
            name='away_odd',
        ),
        migrations.RemoveField(
            model_name='event',
            name='creation_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
        migrations.RemoveField(
            model_name='event',
            name='draw_odd',
        ),
        migrations.RemoveField(
            model_name='event',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='home_name',
        ),
        migrations.RemoveField(
            model_name='event',
            name='home_odd',
        ),
        migrations.RemoveField(
            model_name='event',
            name='open',
        ),
        migrations.RemoveField(
            model_name='event',
            name='result',
        ),
        migrations.AddField(
            model_name='bet',
            name='amount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bet',
            name='chosen_event',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bet',
            name='settled',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bet',
            name='reward',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='bet',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.wallet'),
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('status', models.IntegerField()),
                ('odd', models.FloatField()),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.market')),
            ],
        ),
        migrations.AddField(
            model_name='market',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.event'),
        ),
        migrations.AddField(
            model_name='bet',
            name='chosen_variant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.variant'),
            preserve_default=False,
        ),
    ]
