# Generated by Django 3.1.8 on 2021-05-21 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210521_0535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='market',
            name='status',
        ),
        migrations.AddField(
            model_name='variant',
            name='settlement',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
