# Generated by Django 3.1.8 on 2021-05-21 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210521_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
